name = "uni_concurent_wave"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
maintainers-logins = ["github-username"]

executables = ["uni_concurent_wave"]
